# 链接样式，参考 http://jekyllrb.com/docs/permalinks
permalink: /:categories/:year-:month/:title.html

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: pygments
paginate: 5

markdown: redcarpet             # markdown 语法解释引擎
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]
# 参考 http://github.com/vmg/redcarpet/blob/master/README.markdown

# 核心设置
title : Oo
tagline: 水，利万物而不争
keywords : linux ,machine learning ,data mining , R , Hadoop ,Spark
description: happy wife , happy life ...
author :
  name :  Oo
  email : 
  github : dcycome
  gitcafe : 
  twitter :
  facebook : thinkhm 
  feedburner :
  weibo : SupreDream

# 域名连接
production_url : http://dcycome.vicp.net

# 七牛云，http://<Bucket>.qiniudn.com
qiniudn : http://dcycome.qiniudn.com 

# Jekyll Bootstrap
JB :
  version : 0.3.0

  BASE_PATH : false                 # 如果不懂参数，请不要更改
  ASSET_PATH : false                # 同上

  # page
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml

 # comment
comments:
    provider: duoshuo
    duoshuo:
        name: havanna
        rcomments:
            num: 10
            avatar: 0
            time: 0
            title: 0
            admin: 0
            length: 12
            
            
  # 网站统计
  analytics :
    provider : baidu                # 采用那种统计，baidu 或 google ...
    google :
        tracking_id : 'UA-53828211-1'
    getclicky :
        site_id :
    mixpanel :
        token : '_MIXPANEL_TOKEN_'
    piwik :
        baseURL : 'myserver.tld/piwik' # Piwik installation address (without protocol)
        idsite : '1'                   # the id of the site on Piwik
    baidu :
        siteid: 3Fd12e24c8f6f6389d28e560ce2f9f620d      # 百度统计 js 代码后的字符串

  # 一键分享
  sharing :
    provider : baidu

  # 友情链接
  blogroll : false                   # true 开启，留空或 false 关闭
  brlist :
    - text : 刘静的博客
      url : //upliu.net/
    - text : 小天地，大世界
      url : //www.lyblog.net/
    - text : 清风的网络空间
      url : //phpcj.org/
