# Site settings
title: "Oo's Space"
description: "linux, gentoo, internet, sql, jekyll, BSD, MAC, havee"
keywords: "linux, gentoo, internet, sql, jekyll, BSD, MAC, havee"
baseurl: ""
url: "//dcycome.vicp.net"
highlighter: pygments
paginate: 5
author:
    name: Oo
    github: dcycome
    email:
    gitcafe: 
    twitter:
    facebook:
    googleplus:
    weibo: SupreDream
qiniudn: //havee.qiniudn.com
atom_path: /atom.xml
rss_path: /rss.xml

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]
permalink: /:categories/:year-:month/:title.html

# comment
comments:
    provider: duoshuo
    duoshuo:
        name: dcycome
        rcomments:
            num: 10
            avatar: 0
            time: 0
            title: 0
            admin: 0
            length: 12
# 网站统计
analytics:
    baidu:
        siteid:         # 百度统计 js 代码后的字符串

# blogroll
blogroll: false
brlist:
    - text: "刘静的博客"
      url : //upliu.net/
    - text: "小天地，大世界"
      url : //www.lyblog.net/
    - text: "清风的网络空间"
      url : //phpcj.org/
